<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="job_api_test.JobApiTest-20180301163055" tests="11" time="12.533">
	<testcase classname="job_api_test.JobApiTest" name="test_badge" time="1.137"/>
	<testcase classname="job_api_test.JobApiTest" name="test_cache" time="1.146"/>
	<testcase classname="job_api_test.JobApiTest" name="test_consoleupdate" time="1.517"/>
	<testcase classname="job_api_test.JobApiTest" name="test_create_jobs" time="1.165"/>
	<testcase classname="job_api_test.JobApiTest" name="test_job" time="1.109"/>
	<testcase classname="job_api_test.JobApiTest" name="test_markup" time="0.935"/>
	<testcase classname="job_api_test.JobApiTest" name="test_output" time="1.181"/>
	<testcase classname="job_api_test.JobApiTest" name="test_setrunning" time="1.032"/>
	<testcase classname="job_api_test.JobApiTest" name="test_source" time="1.309"/>
	<testcase classname="job_api_test.JobApiTest" name="test_stats" time="1.032"/>
	<testcase classname="job_api_test.JobApiTest" name="test_testresult" time="0.970">
		<error message="add_file() takes at least 3 arguments (2 given)" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/infrabox/context/infrabox/test/api/job_api_test.py", line 149, in test_testresult
    content_type='multipart/form-data')
  File "/infrabox/context/infrabox/test/api/temp_tools.py", line 76, in post
    content_type=content_type)
  File "/usr/lib/python2.7/site-packages/werkzeug/test.py", line 788, in post
    return self.open(*args, **kw)
  File "/usr/lib/python2.7/site-packages/flask/testing.py", line 122, in open
    builder = make_test_environ_builder(self.application, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask/testing.py", line 37, in make_test_environ_builder
    return EnvironBuilder(path, base_url, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/werkzeug/test.py", line 338, in __init__
    self._add_file_from_data(key, value)
  File "/usr/lib/python2.7/site-packages/werkzeug/test.py", line 355, in _add_file_from_data
    self.files.add_file(key, **value)
TypeError: add_file() takes at least 3 arguments (2 given)
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[200
200
200
200
200
200
200
200
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
